//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ROPAModel", "fk_UpcomingRoles_pid", "UpcomingRole", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ROPAModel.UpcomingRole), "UpcmomingSurveyor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ROPAModel.UpcmomingSurveyor), true)]
[assembly: EdmRelationshipAttribute("ROPAModel", "fk_UpcomingAppstauts_Appid", "UpcomingAppstatu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ROPAModel.UpcomingAppstatu), "UpcmomingSurveyor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ROPAModel.UpcmomingSurveyor), true)]
[assembly: EdmRelationshipAttribute("ROPAModel", "fk_Country_countrycode", "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ROPAModel.Country), "FeedBackForm", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ROPAModel.FeedBackForm), true)]
[assembly: EdmRelationshipAttribute("ROPAModel", "fk_UpcmomingSurveyor", "UpcmomingSurveyor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ROPAModel.UpcmomingSurveyor), "UploadFile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ROPAModel.UploadFile), true)]

#endregion

namespace ROPAModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ROPAEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ROPAEntities object using the connection string found in the 'ROPAEntities' section of the application configuration file.
        /// </summary>
        public ROPAEntities() : base("name=ROPAEntities", "ROPAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ROPAEntities object.
        /// </summary>
        public ROPAEntities(string connectionString) : base(connectionString, "ROPAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ROPAEntities object.
        /// </summary>
        public ROPAEntities(EntityConnection connection) : base(connection, "ROPAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UpcmomingSurveyor> UpcmomingSurveyors
        {
            get
            {
                if ((_UpcmomingSurveyors == null))
                {
                    _UpcmomingSurveyors = base.CreateObjectSet<UpcmomingSurveyor>("UpcmomingSurveyors");
                }
                return _UpcmomingSurveyors;
            }
        }
        private ObjectSet<UpcmomingSurveyor> _UpcmomingSurveyors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UpcomingRole> UpcomingRoles
        {
            get
            {
                if ((_UpcomingRoles == null))
                {
                    _UpcomingRoles = base.CreateObjectSet<UpcomingRole>("UpcomingRoles");
                }
                return _UpcomingRoles;
            }
        }
        private ObjectSet<UpcomingRole> _UpcomingRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UpcomingAppstatu> UpcomingAppstatus
        {
            get
            {
                if ((_UpcomingAppstatus == null))
                {
                    _UpcomingAppstatus = base.CreateObjectSet<UpcomingAppstatu>("UpcomingAppstatus");
                }
                return _UpcomingAppstatus;
            }
        }
        private ObjectSet<UpcomingAppstatu> _UpcomingAppstatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Country> Countries
        {
            get
            {
                if ((_Countries == null))
                {
                    _Countries = base.CreateObjectSet<Country>("Countries");
                }
                return _Countries;
            }
        }
        private ObjectSet<Country> _Countries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FeedBackForm> FeedBackForms
        {
            get
            {
                if ((_FeedBackForms == null))
                {
                    _FeedBackForms = base.CreateObjectSet<FeedBackForm>("FeedBackForms");
                }
                return _FeedBackForms;
            }
        }
        private ObjectSet<FeedBackForm> _FeedBackForms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UploadFile> UploadFiles
        {
            get
            {
                if ((_UploadFiles == null))
                {
                    _UploadFiles = base.CreateObjectSet<UploadFile>("UploadFiles");
                }
                return _UploadFiles;
            }
        }
        private ObjectSet<UploadFile> _UploadFiles;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UpcmomingSurveyors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUpcmomingSurveyors(UpcmomingSurveyor upcmomingSurveyor)
        {
            base.AddObject("UpcmomingSurveyors", upcmomingSurveyor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UpcomingRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUpcomingRoles(UpcomingRole upcomingRole)
        {
            base.AddObject("UpcomingRoles", upcomingRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UpcomingAppstatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUpcomingAppstatus(UpcomingAppstatu upcomingAppstatu)
        {
            base.AddObject("UpcomingAppstatus", upcomingAppstatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCountries(Country country)
        {
            base.AddObject("Countries", country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FeedBackForms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeedBackForms(FeedBackForm feedBackForm)
        {
            base.AddObject("FeedBackForms", feedBackForm);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UploadFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUploadFiles(UploadFile uploadFile)
        {
            base.AddObject("UploadFiles", uploadFile);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ROPAModel", Name="Country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="countryId">Initial value of the CountryId property.</param>
        /// <param name="countrycode">Initial value of the countrycode property.</param>
        public static Country CreateCountry(global::System.Int32 countryId, global::System.String countrycode)
        {
            Country country = new Country();
            country.CountryId = countryId;
            country.countrycode = countrycode;
            return country;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                OnCountryIdChanging(value);
                ReportPropertyChanging("CountryId");
                _CountryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryId");
                OnCountryIdChanged();
            }
        }
        private global::System.Int32 _CountryId;
        partial void OnCountryIdChanging(global::System.Int32 value);
        partial void OnCountryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String countrycode
        {
            get
            {
                return _countrycode;
            }
            set
            {
                if (_countrycode != value)
                {
                    OncountrycodeChanging(value);
                    ReportPropertyChanging("countrycode");
                    _countrycode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("countrycode");
                    OncountrycodeChanged();
                }
            }
        }
        private global::System.String _countrycode;
        partial void OncountrycodeChanging(global::System.String value);
        partial void OncountrycodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryName
        {
            get
            {
                return _CountryName;
            }
            set
            {
                OnCountryNameChanging(value);
                ReportPropertyChanging("CountryName");
                _CountryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryName");
                OnCountryNameChanged();
            }
        }
        private global::System.String _CountryName;
        partial void OnCountryNameChanging(global::System.String value);
        partial void OnCountryNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_Country_countrycode", "FeedBackForm")]
        public EntityCollection<FeedBackForm> FeedBackForms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FeedBackForm>("ROPAModel.fk_Country_countrycode", "FeedBackForm");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FeedBackForm>("ROPAModel.fk_Country_countrycode", "FeedBackForm", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ROPAModel", Name="FeedBackForm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FeedBackForm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FeedBackForm object.
        /// </summary>
        /// <param name="feedBackId">Initial value of the FeedBackId property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="emailId">Initial value of the EmailId property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        /// <param name="addres">Initial value of the Addres property.</param>
        /// <param name="commments">Initial value of the Commments property.</param>
        /// <param name="insertDate">Initial value of the insertDate property.</param>
        /// <param name="countrycode">Initial value of the countrycode property.</param>
        public static FeedBackForm CreateFeedBackForm(global::System.Int32 feedBackId, global::System.String firstName, global::System.String emailId, global::System.String phoneNumber, global::System.String addres, global::System.String commments, global::System.DateTime insertDate, global::System.String countrycode)
        {
            FeedBackForm feedBackForm = new FeedBackForm();
            feedBackForm.FeedBackId = feedBackId;
            feedBackForm.FirstName = firstName;
            feedBackForm.EmailId = emailId;
            feedBackForm.PhoneNumber = phoneNumber;
            feedBackForm.Addres = addres;
            feedBackForm.Commments = commments;
            feedBackForm.insertDate = insertDate;
            feedBackForm.countrycode = countrycode;
            return feedBackForm;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeedBackId
        {
            get
            {
                return _FeedBackId;
            }
            set
            {
                if (_FeedBackId != value)
                {
                    OnFeedBackIdChanging(value);
                    ReportPropertyChanging("FeedBackId");
                    _FeedBackId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FeedBackId");
                    OnFeedBackIdChanged();
                }
            }
        }
        private global::System.Int32 _FeedBackId;
        partial void OnFeedBackIdChanging(global::System.Int32 value);
        partial void OnFeedBackIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailId
        {
            get
            {
                return _EmailId;
            }
            set
            {
                OnEmailIdChanging(value);
                ReportPropertyChanging("EmailId");
                _EmailId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailId");
                OnEmailIdChanged();
            }
        }
        private global::System.String _EmailId;
        partial void OnEmailIdChanging(global::System.String value);
        partial void OnEmailIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Addres
        {
            get
            {
                return _Addres;
            }
            set
            {
                OnAddresChanging(value);
                ReportPropertyChanging("Addres");
                _Addres = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Addres");
                OnAddresChanged();
            }
        }
        private global::System.String _Addres;
        partial void OnAddresChanging(global::System.String value);
        partial void OnAddresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Commments
        {
            get
            {
                return _Commments;
            }
            set
            {
                OnCommmentsChanging(value);
                ReportPropertyChanging("Commments");
                _Commments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Commments");
                OnCommmentsChanged();
            }
        }
        private global::System.String _Commments;
        partial void OnCommmentsChanging(global::System.String value);
        partial void OnCommmentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime insertDate
        {
            get
            {
                return _insertDate;
            }
            set
            {
                OninsertDateChanging(value);
                ReportPropertyChanging("insertDate");
                _insertDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("insertDate");
                OninsertDateChanged();
            }
        }
        private global::System.DateTime _insertDate;
        partial void OninsertDateChanging(global::System.DateTime value);
        partial void OninsertDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String countrycode
        {
            get
            {
                return _countrycode;
            }
            set
            {
                OncountrycodeChanging(value);
                ReportPropertyChanging("countrycode");
                _countrycode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("countrycode");
                OncountrycodeChanged();
            }
        }
        private global::System.String _countrycode;
        partial void OncountrycodeChanging(global::System.String value);
        partial void OncountrycodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_Country_countrycode", "Country")]
        public Country Country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("ROPAModel.fk_Country_countrycode", "Country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("ROPAModel.fk_Country_countrycode", "Country").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Country> CountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("ROPAModel.fk_Country_countrycode", "Country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Country>("ROPAModel.fk_Country_countrycode", "Country", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ROPAModel", Name="UpcmomingSurveyor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UpcmomingSurveyor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UpcmomingSurveyor object.
        /// </summary>
        /// <param name="surApp_Id">Initial value of the SurApp_Id property.</param>
        public static UpcmomingSurveyor CreateUpcmomingSurveyor(global::System.Int32 surApp_Id)
        {
            UpcmomingSurveyor upcmomingSurveyor = new UpcmomingSurveyor();
            upcmomingSurveyor.SurApp_Id = surApp_Id;
            return upcmomingSurveyor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurApp_Id
        {
            get
            {
                return _SurApp_Id;
            }
            set
            {
                if (_SurApp_Id != value)
                {
                    OnSurApp_IdChanging(value);
                    ReportPropertyChanging("SurApp_Id");
                    _SurApp_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SurApp_Id");
                    OnSurApp_IdChanged();
                }
            }
        }
        private global::System.Int32 _SurApp_Id;
        partial void OnSurApp_IdChanging(global::System.Int32 value);
        partial void OnSurApp_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ApplyAsRole
        {
            get
            {
                return _ApplyAsRole;
            }
            set
            {
                OnApplyAsRoleChanging(value);
                ReportPropertyChanging("ApplyAsRole");
                _ApplyAsRole = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApplyAsRole");
                OnApplyAsRoleChanged();
            }
        }
        private Nullable<global::System.Int32> _ApplyAsRole;
        partial void OnApplyAsRoleChanging(Nullable<global::System.Int32> value);
        partial void OnApplyAsRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AppId
        {
            get
            {
                return _AppId;
            }
            set
            {
                OnAppIdChanging(value);
                ReportPropertyChanging("AppId");
                _AppId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppId");
                OnAppIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AppId;
        partial void OnAppIdChanging(Nullable<global::System.Int32> value);
        partial void OnAppIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifedDate
        {
            get
            {
                return _ModifedDate;
            }
            set
            {
                OnModifedDateChanging(value);
                ReportPropertyChanging("ModifedDate");
                _ModifedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifedDate");
                OnModifedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifedDate;
        partial void OnModifedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLogin;
        partial void OnLastLoginChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAILID
        {
            get
            {
                return _EMAILID;
            }
            set
            {
                OnEMAILIDChanging(value);
                ReportPropertyChanging("EMAILID");
                _EMAILID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAILID");
                OnEMAILIDChanged();
            }
        }
        private global::System.String _EMAILID;
        partial void OnEMAILIDChanging(global::System.String value);
        partial void OnEMAILIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_UpcomingRoles_pid", "UpcomingRole")]
        public UpcomingRole UpcomingRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcomingRole>("ROPAModel.fk_UpcomingRoles_pid", "UpcomingRole").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcomingRole>("ROPAModel.fk_UpcomingRoles_pid", "UpcomingRole").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UpcomingRole> UpcomingRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcomingRole>("ROPAModel.fk_UpcomingRoles_pid", "UpcomingRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UpcomingRole>("ROPAModel.fk_UpcomingRoles_pid", "UpcomingRole", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_UpcomingAppstauts_Appid", "UpcomingAppstatu")]
        public UpcomingAppstatu UpcomingAppstatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcomingAppstatu>("ROPAModel.fk_UpcomingAppstauts_Appid", "UpcomingAppstatu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcomingAppstatu>("ROPAModel.fk_UpcomingAppstauts_Appid", "UpcomingAppstatu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UpcomingAppstatu> UpcomingAppstatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcomingAppstatu>("ROPAModel.fk_UpcomingAppstauts_Appid", "UpcomingAppstatu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UpcomingAppstatu>("ROPAModel.fk_UpcomingAppstauts_Appid", "UpcomingAppstatu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_UpcmomingSurveyor", "UploadFile")]
        public EntityCollection<UploadFile> UploadFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UploadFile>("ROPAModel.fk_UpcmomingSurveyor", "UploadFile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UploadFile>("ROPAModel.fk_UpcmomingSurveyor", "UploadFile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ROPAModel", Name="UpcomingAppstatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UpcomingAppstatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UpcomingAppstatu object.
        /// </summary>
        /// <param name="appId">Initial value of the AppId property.</param>
        public static UpcomingAppstatu CreateUpcomingAppstatu(global::System.Int32 appId)
        {
            UpcomingAppstatu upcomingAppstatu = new UpcomingAppstatu();
            upcomingAppstatu.AppId = appId;
            return upcomingAppstatu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppId
        {
            get
            {
                return _AppId;
            }
            set
            {
                if (_AppId != value)
                {
                    OnAppIdChanging(value);
                    ReportPropertyChanging("AppId");
                    _AppId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppId");
                    OnAppIdChanged();
                }
            }
        }
        private global::System.Int32 _AppId;
        partial void OnAppIdChanging(global::System.Int32 value);
        partial void OnAppIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AppStatus
        {
            get
            {
                return _AppStatus;
            }
            set
            {
                OnAppStatusChanging(value);
                ReportPropertyChanging("AppStatus");
                _AppStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AppStatus");
                OnAppStatusChanged();
            }
        }
        private global::System.String _AppStatus;
        partial void OnAppStatusChanging(global::System.String value);
        partial void OnAppStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_UpcomingAppstauts_Appid", "UpcmomingSurveyor")]
        public EntityCollection<UpcmomingSurveyor> UpcmomingSurveyors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UpcmomingSurveyor>("ROPAModel.fk_UpcomingAppstauts_Appid", "UpcmomingSurveyor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UpcmomingSurveyor>("ROPAModel.fk_UpcomingAppstauts_Appid", "UpcmomingSurveyor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ROPAModel", Name="UpcomingRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UpcomingRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UpcomingRole object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        public static UpcomingRole CreateUpcomingRole(global::System.Int32 roleId)
        {
            UpcomingRole upcomingRole = new UpcomingRole();
            upcomingRole.RoleId = roleId;
            return upcomingRole;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_UpcomingRoles_pid", "UpcmomingSurveyor")]
        public EntityCollection<UpcmomingSurveyor> UpcmomingSurveyors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UpcmomingSurveyor>("ROPAModel.fk_UpcomingRoles_pid", "UpcmomingSurveyor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UpcmomingSurveyor>("ROPAModel.fk_UpcomingRoles_pid", "UpcmomingSurveyor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ROPAModel", Name="UploadFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UploadFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UploadFile object.
        /// </summary>
        /// <param name="uPloadId">Initial value of the UPloadId property.</param>
        public static UploadFile CreateUploadFile(global::System.Int32 uPloadId)
        {
            UploadFile uploadFile = new UploadFile();
            uploadFile.UPloadId = uPloadId;
            return uploadFile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UPloadId
        {
            get
            {
                return _UPloadId;
            }
            set
            {
                if (_UPloadId != value)
                {
                    OnUPloadIdChanging(value);
                    ReportPropertyChanging("UPloadId");
                    _UPloadId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UPloadId");
                    OnUPloadIdChanged();
                }
            }
        }
        private global::System.Int32 _UPloadId;
        partial void OnUPloadIdChanging(global::System.Int32 value);
        partial void OnUPloadIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SurApp_Id
        {
            get
            {
                return _SurApp_Id;
            }
            set
            {
                OnSurApp_IdChanging(value);
                ReportPropertyChanging("SurApp_Id");
                _SurApp_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurApp_Id");
                OnSurApp_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _SurApp_Id;
        partial void OnSurApp_IdChanging(Nullable<global::System.Int32> value);
        partial void OnSurApp_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                OnGUIDChanging(value);
                ReportPropertyChanging("GUID");
                _GUID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GUID");
                OnGUIDChanged();
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIleFor
        {
            get
            {
                return _FIleFor;
            }
            set
            {
                OnFIleForChanging(value);
                ReportPropertyChanging("FIleFor");
                _FIleFor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIleFor");
                OnFIleForChanged();
            }
        }
        private global::System.String _FIleFor;
        partial void OnFIleForChanging(global::System.String value);
        partial void OnFIleForChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fileext
        {
            get
            {
                return _fileext;
            }
            set
            {
                OnfileextChanging(value);
                ReportPropertyChanging("fileext");
                _fileext = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fileext");
                OnfileextChanged();
            }
        }
        private global::System.String _fileext;
        partial void OnfileextChanging(global::System.String value);
        partial void OnfileextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ROPAModel", "fk_UpcmomingSurveyor", "UpcmomingSurveyor")]
        public UpcmomingSurveyor UpcmomingSurveyor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcmomingSurveyor>("ROPAModel.fk_UpcmomingSurveyor", "UpcmomingSurveyor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcmomingSurveyor>("ROPAModel.fk_UpcmomingSurveyor", "UpcmomingSurveyor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UpcmomingSurveyor> UpcmomingSurveyorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UpcmomingSurveyor>("ROPAModel.fk_UpcmomingSurveyor", "UpcmomingSurveyor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UpcmomingSurveyor>("ROPAModel.fk_UpcmomingSurveyor", "UpcmomingSurveyor", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
